In [1]:
import random

import h5py
import numpy as np
import torchvision
import torch
from matplotlib import pyplot as plt
from PIL import Image
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

In [2]:
file = h5py.File(r"E:\train.h5","r")

In [4]:
file.close()

In [3]:
file.keys()

<KeysViewHDF5 ['sampleData', 'sampleType']>

In [3]:
img:np.ndarray=file['sampleData'][:]
label:np.ndarray=file['sampleType'][:]
name=['singlepulse','freqdiv','LFM','QFM','2FSK','4FSK','BPSK','QPSK']

In [4]:
label.shape,img.shape

((5, 40000), (195, 64, 40000))

In [5]:
img_type:np.ndarray=label[0,:].flatten()
img_snr:np.ndarray=label[1,:].flatten()
img_type.shape

(40000,)

In [6]:
QPSK=img[:,:,img_type==8]
BPSK=img[:,:,img_type==7]

In [7]:
x=BPSK[:,:,0]

In [17]:
%matplotlib
import random
i=random.randint(0,4999)
plt.subplot(121)
plt.imshow(BPSK[:,:,i].transpose(),cmap="gray")
plt.title("BPSK")
plt.subplot(122)
plt.imshow(QPSK[:,:,i].transpose(),cmap="gray")
plt.title("QPSK")
plt.show()

Using matplotlib backend: TkAgg


In [ ]:
y=torch.tensor(label,dtype=torch.long)
y=y[0,:]
y[y==8]=7
y

__将BPSK和QPSK合并为一种__

In [22]:
img_type[img_type==8]=7

In [46]:
x=np.array(range(0,800))

In [48]:
x[img_type==2]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [53]:
x[img_snr==10]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

## 根据类型提取数据

In [3]:
path = r"E:\test.h5"
h5 = h5py.File(path)
g_label = h5['sampleType'][:]
g_data = h5['sampleData'][:, :, :]
h5.close()
toTensor = torchvision.transforms.ToTensor()

In [4]:
def filter(type=None, snr=None) -> np.ndarray:
    full = (g_label[0, :] != None)
    if (type != None):
        full = full & (g_label[0, :] == type)
    if (snr != None):
        full = full & (g_label[1, :] == snr)
    # 将TrueFalse数组转换为索引
    ids = np.argwhere(full).reshape(-1)
    return ids
filter(1,2)

array([19, 35], dtype=int64)

In [5]:
ids=filter(1,2)

In [7]:
g_data[:,:,ids].shape

(196, 64, 2)

In [8]:
toTensor(g_data[:,:,ids]).shape

torch.Size([2, 196, 64])

In [9]:
label[:,filter(1,2)].reshape(5,-1).shape

(5, 2)

In [11]:
img[:,:,filter(1,2)].shape

(196, 64, 1, 2)